### ISSUE TITLE
problem with matrix_client package.

### ISSUE THREAD

**Issue by mebjas** [Spferical/matrix-chatbot#1]
```
2017-01-04 09:55:38,608 root INFO loading brain
2017-01-04 09:55:39,055 root INFO initial event stream
2017-01-04 09:55:42,585 root INFO starting listener thread
2017-01-04 09:55:43,028 matrix_client.client ERROR Exception thrown during sync
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/matrix_client/client.py", line 255, in listen_forever
    self._sync(timeout_ms)
  File "/usr/local/lib/python2.7/dist-packages/matrix_client/client.py", line 356, in _sync
    room._put_event(event)
  File "/usr/local/lib/python2.7/dist-packages/matrix_client/client.py", line 484, in _put_event
    listener(self, event)
TypeError: 'dict' object is not callable
```

it's throwing this error when ever library attempts to sync events

**Comment by Spferical** [comment]
Interesting. What version of the library are you using? The version I'm developing with right now is 0.0.3 (and I should probably specify in the readme since I haven't been testing with the latest version, 0.0.5).

**Comment by mebjas** [comment]
Oh yes I'm using `matrix-client v0.0.5`. Also it seems it's issue with the matrix-client sdk not this project.

**Comment by mebjas** [comment]
And yes I verified it works with `0.0.3`

**Comment by Spferical** [comment]
Cool, looks like it's an issue with v0.0.5 that is fixed in the latest git version of the sdk. Next time they make a release it should contain the fix. Though 0.0.3 is the only one I officially support right now. Glad it works!
